### PR TITLE
Fixes issue with special characters

### LINKED ISSUE #1: Videos with "strange" characters freeze the download
Episodes that cause trouble:
Season 0: episode 8 (verfified)
Season 1: episode 235, episode 7 (suspected)

The issue may be due to windows not allowing the "|" (vertical bar, pipe) character in a file name.
I suggest filtering out that character by replacing it with something else like whitespace or maybe "-" (hypen, minus sign)

### PR DESCRIPTION
**Pull request by epeat96**

### CODE REVIEW

**Comment by epeat96** [comment]
Forgot to only stage the modified source file, you can delete the package-lock.json file before accepting the pull request if you want

**Comment by EverlyScott** [comment]
I'm gonna test downloading every episode so it'll probably take a bit

**Comment by EverlyScott** [comment]
Actually my desktop at home is turned off so I'm not able to do that until I get home

**Comment by EverlyScott** [comment]
Everything should, in theory, be working; all the filenames are coming out to be compatible in the test.

**Comment by epeat96** [comment]
Tested with episode 288 titled "Team Building for 2: Trust Fall, Tug-of-War, and More!" output file was: "Team Building for 2_ Trust Fall_ Tug-of-War_ and More_.mp4" with no freeze while trying to download

**Comment by EverlyScott** [comment]
I was able to download a fair amount of episodes but then the app crashed i believe. I'm assuming its an unrelated issue because it has no mention of this so I'll commit this to main.

**Pull request merged**
